name: CrackerNetworkCore-Survival
version: '${version}'
main: me.reptiled.crackernetworkcoresurvival.CrackerNetworkCore
api-version: '1.20'
commands:
  vanish:
    description: Spying on people, creepy
    permission: vanish
    aliases: [v]

  sethome:
    description: Set home

  home:
    description: Teleport to home

  homes:
    description: View your homes

  delhome:
    description: Delete home
    aliases: [deletehome]

  tpa:
    description: Send tpa request to someone

  tpaccept:
    description: Accept tpa requests

  tpadeny:
    description: Deny tpa requests