name: CrackerNetworkCore-Hub
version: '${version}'
main: me.reptiled.core.CrackerNetworkCore
api-version: '1.20'
softdepend: [Luckperms, TAB]
commands:
  vanish:
    description: Spying on people, creepy
    permission: vanish
    aliases: [v]

  discord:
    description: Sends discord link