name: CrackerNetworkCore-Survival
version: '${version}'
main: me.reptiled.crackernetworkcoresurvival.CrackerNetworkCore
api-version: '1.20'
softdepend: [Luckperms, TAB]
commands:
  vanish:
    description: Spying on people, creepy
    permission: vanish
    aliases: [v]

  sethome:
    description: Set home

  home:
    description: Teleport to home

  homes:
    description: View your homes

  delhome:
    description: Delete home
    aliases: [deletehome]

  tpa:
    description: Send tpa request to someone

  tpaccept:
    description: Accept tpa requests

  tpadeny:
    description: Deny tpa requests

  createTeam:
    description: Creates team

  leaveTeam:
    description: Leave your current team

  team:
    description: Team commands

  changeTag:
    description: Change your tag

  channel:
    description: Change channel
    aliases: [c]

  invsee:
    description: View inventory
    permission: invsee